build:
  image: tapanhalani/drone-sbt-docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - echo "hello tapan"
    - docker ps
    - sbt compile
    - echo "successful compilation"
    - sbt package
  publish:
    docker:
      username: tapanhalani
      password: 28march1994
      email: tapanhalani231@gmail.com
      repo: tapanhalani/lyearnscalacopy
      tag: latest
