build:
  image: tapanhalani/drone-sbt-docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib:/var/lib
  commands:
    - echo $DRONE_REPO_NAME
    - echo tapanhalani/lyearnscalacopy:$DRONE_BRANCH
    - ls -a /var/lib
    - mkdir /root/.ivy2
    - cp -a /var/lib/.ivy2/ /root/
    - ls -a /root/.ivy2/
    - DOCKER_API_VERSION=1.22 docker ps
    - sbt compile
    - cp -a /root/.ivy2 /var/lib/
    - ls -a /var/lib/.ivy2
    - sbt package
    - DOCKER_API_VERSION=1.22 sbt docker
    - DOCKER_API_VERSION=1.22 docker tag default/lyearnscalacopy:latest tapanhalani/lyearnscalacopy:$DRONE_BRANCH
    - echo "curl -v  --unix-socket /var/run/docker.sock -H 'X-Registry-Auth:" " $$DOCKER_XAUTH' -X POST http:/images/tapanhalani/lyearnscalacopy/push?tag=$DRONE_BRANCH" > docker_push.sh
    - sh docker_push.sh
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: lyearnScala/web
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
