build:
  image: tapanhalani/drone-sbt-docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - echo "hello tapan"
    - DOCKER_API_VERSION=1.22 docker ps
    - sbt compile
    - echo "successful compilation"
    - touch tapanhalani.txt
    - sbt package
    - DOCKER_API_VERSION=1.22 sbt docker
    - DOCKER_API_VERSION=1.22 docker tag default/lyearnscalacopy:latest tapanhalani/lyearnscalacopy:dronebuild
    - echo "curl -v  --unix-socket /var/run/docker.sock -H 'X-Registry-Auth:" " eyAidXNlcm5hbWUiOiAidGFwYW5oYWxhbmkiLCAicGFzc3dvcmQiOiAiMjhtYXJjaDE5OTQiLCAiZW1haWwiOiAidGFwYW5oYWxhbmkyMzFAZ21haWwuY29tIiB9Cg==' -X POST http:/images/tapanhalani/lyearnscalacopy/push?tag=dronebuild" > docker_push.sh
    - sh docker_push.sh
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: BF754D49D231B3FB16ED
    secret_key: 554b7afe3b4b630669df4365ff6a346185ab1517
    service: lyearnScala/web_1
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: BF754D49D231B3FB16ED
    secret_key: 554b7afe3b4b630669df4365ff6a346185ab1517
    service: lyearnScala/web_2
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: BF754D49D231B3FB16ED
    secret_key: 554b7afe3b4b630669df4365ff6a346185ab1517
    service: lyearnScala/web_3
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
