build:
  image: tapanhalani/drone-sbt-docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib:/var/lib
  commands:
    - echo tapanhalani/lyearnscalacopy:$DRONE_BRANCH
    - ls -a /var/lib
    - mkdir /root/.ivy2
    - cp -a /var/lib/.ivy2/ /root/
    - ls -a /root/.ivy2/
    - DOCKER_API_VERSION=1.22 docker ps
    - sbt compile
    - cp -a /root/.ivy2 /var/lib/
    - ls -a /var/lib/.ivy2
    - echo "successful compilation"
    - sbt package
    - DOCKER_API_VERSION=1.22 sbt docker
    - DOCKER_API_VERSION=1.22 docker tag default/lyearnscalacopy:latest tapanhalani/lyearnscalacopy:$DRONE_BRANCH
    - echo "curl -v  --unix-socket /var/run/docker.sock -H 'X-Registry-Auth:" " eyAidXNlcm5hbWUiOiAidGFwYW5oYWxhbmkiLCAicGFzc3dvcmQiOiAiMjhtYXJjaDE5OTQiLCAiZW1haWwiOiAidGFwYW5oYWxhbmkyMzFAZ21haWwuY29tIiB9Cg==' -X POST http:/images/tapanhalani/lyearnscalacopy/push?tag=$DRONE_BRANCH" > docker_push.sh
    - sh docker_push.sh
