build:
  image: tapanhalani/drone-sbt-docker
  pull: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib:/var/lib
  commands:
    - ls -a /var/lib
    - echo -e 'DIRECTORY=/var/lib/.ivy2\nif [ -d "$DIRECTORY" ]; then\n\tmkdir /root/.ivy2\n\tcp -a /var/lib/.ivy2/ /root/\n\tls -a /root/.ivy2/\nelse\n\techo ".ivy2 directory not found."\nfi' > cache_script.sh
    - sh cache_script.sh
    - DOCKER_API_VERSION=1.22 docker ps
    - sbt compile
    - cp -a /root/.ivy2 /var/lib/
    - ls -a /var/lib/.ivy2
    - sbt package
    - DOCKER_API_VERSION=1.22 sbt docker
    - DOCKER_API_VERSION=1.22 docker tag default/lyearnscalacopy:latest tapanhalani/lyearnscalacopy:$DRONE_BRANCH
    - echo "curl -v  --unix-socket /var/run/docker.sock -H 'X-Registry-Auth:" " $$DOCKER_XAUTH' -X POST http:/images/tapanhalani/lyearnscalacopy/push?tag=$DRONE_BRANCH" > docker_push.sh
    - sh docker_push.sh
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: lyearnScala/lyearnScala
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
