build:
  image: e8kor/sbt-docker
  commands:
    - echo "hello tapan"
    - docker
    - sudo service docker start
    - sbt compile
    - echo "successful compilation"
    - sbt package
    - sbt docker
