build:
  image: tapanhalani/drone-sbt-docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - echo "hello tapan"
    - DOCKER_API_VERSION=1.22 docker ps
    - sbt compile
    - echo "successful compilation"
    - touch tapanhalani.txt
    - sbt package
    - DOCKER_API_VERSION=1.22 sbt docker
    - DOCKER_API_VERSION=1.22 docker tag default/lyearnscalacopy:latest tapanhalani/lyearnscalacopy:dronebuild
publish:
  docker:
    storage_driver: overlay
    username: tapanhalani
    password: $$DOCKERHUB_PASSWORD
    email: tapanhalani231@gmail.com
    repo: tapanhalani/lyearnscalacopy
    tag: dronebuild
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: d94a29181a7a454b0930
    secret_key: 554b7afe3b4b630669df4365ff6a346185ab1517
    service: lyearnScala/web_1
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: d94a29181a7a454b0930
    secret_key: 554b7afe3b4b630669df4365ff6a346185ab1517
    service: lyearnScala/web_2
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
deploy:
  rancher:
    url: http://159.203.162.222:8080/v1/projects/1a5
    access_key: d94a29181a7a454b0930
    secret_key: 554b7afe3b4b630669df4365ff6a346185ab1517
    service: lyearnScala/web_3
    docker_image: tapanhalani/lyearnscalacopy:dronebuild
