build:
  image: tapanhalani/drone-sbt-docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - echo "hello tapan"
    - docker ps
    - sbt compile
    - echo "successful compilation"
    - sbt package
    - sbt docker
